# 根据项目再决定开启lint规则
disabled_rules:
- identifier_name
- line_length
- cyclomatic_complexity
- function_body_length
- operator_whitespace
- file_length
- unneeded_break_in_switch
- implicit_getter
- unused_setter_value
- type_body_length
- function_parameter_count
- computed_accessors_order
- for_where
- unused_optional_binding
- orphaned_doc_comment
- multiple_closures_with_trailing_closure
- block_based_kvo
- vertical_parameter_alignment
- redundant_optional_initialization
- force_cast
- shorthand_operator
- large_tuple
- comment_spacing
- weak_delegate
- trailing_comma
- comma
